# Generated by Django 5.0.3 on 2024-04-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-pk'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
