# Generated by Django 5.0.3 on 2024-04-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_alter_city_options'),
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Number of train')),
                ('travel_time', models.PositiveSmallIntegerField(verbose_name='Time in travel')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rout_from_city', to='cities.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rout_to_city', to='cities.city')),
                ('trains', models.ManyToManyField(to='train.train', verbose_name='List of trains')),
            ],
        ),
    ]
